### ISSUE TITLE
Rotate PDF page and pagePaintCallbacks

### ISSUE THREAD

**Issue by JElgar** [espresso3389/pdfrx#249]
I am using pdfrx to render a single page of a PDF at a time using `layoutPages`.
 
Is there any mechanism to allow the user to rotate the page they are viewing (with anything added to the page with pagePaintCallbacks also rotated)?

**Comment by JElgar** [comment]
Ok so making slow progress on this one. So far Ive found a bit of a hack where we can wrap the CustomPaint inside the interactive viewer with a transformed container and it successfully renders the page rotated.

```
                          child: Container(
                            transformAlignment: Alignment.center,
                            transform: new Matrix4.identity()..rotateZ(90 * pi / 180),
                            child: CustomPaint(
                              foregroundPainter:
                                  _CustomPainter.fromFunction(_customPaint),
                              size: _layout!.documentSize,
                            ),
                          ),

```

The caveat being it seems to break some others things like globalToLocal as the local coordinates are now rotated.

**Comment by espresso3389** [comment]
I've been working on it and made some changes to lower level APIs (f24f6f44f7bf5f8a67670399ab85e14162c616d2); every page method has `rotationOverride` parameter to override the page's default rotation.

My idea is that layoutPages should have array of `rotationOverride` entries corresponding to the pages. But I should consider more to keep the consitency with the existing behavior...

Anyway, it's not a small change and it takes relatively long...

**Comment by dkupl** [comment]
What is the current status of this enhancement?
By the way, thank you for the library. It works really well.

**Comment by espresso3389** [comment]
On the git master, now pdfrx supports page rotation:

https://github.com/espresso3389/pdfrx/blob/master/doc/PDF-Page-Manipulation.md#page-rotation

If you update `PdfDocument.pages`, PdfViewer automatically refreshes the view.

**Comment by dkupl** [comment]
Hello, I have a problem getting version from master branch.
Any combination for pdfrx or pdfrx_engine (git,specific version) don't work for flutter pub get.
I will wait for new version from pub.dev.

```
[pubspec.yaml ....]
pdfrx:
    git:
      url: https://github.com/espresso3389/pdfrx.git
      ref: master
      path: packages/pdfrx

  pdfrx_engine:
    git:
      url: https://github.com/espresso3389/pdfrx.git
      ref: master
      path: packages/pdfrx_engine
[...pubspec.yaml]
```

**After `flutter pub get` the error is:** 

```
Resolving dependencies... 
Because dossier_viewer_frontend depends on pdfrx from git which depends on pdfrx_engine ^0.2.4, pdfrx_engine from hosted is required.
So, because dossier_viewer_frontend depends on pdfrx_engine from git, version solving failed.
```

**Comment by espresso3389** [comment]
To use pdfrx on git, you should specify the version on `dependency_overrides` rather than `dependencies`;

```yaml
dependencies:
  # versions here does not matter; any versions are OK
  pdfrx:
  pdfrx_engine:

dependency_overrides:
  pdfrx:
    git:
      url: https://github.com/espresso3389/pdfrx.git
      ref: master
      path: packages/pdfrx

  pdfrx_engine:
    git:
      url: https://github.com/espresso3389/pdfrx.git
      ref: master
      path: packages/pdfrx_engine
```
