### ISSUE TITLE
Got ANALYSIS ISSUE on pub.dev due to Flutter/Dart version constraints

### ISSUE THREAD

**Issue by espresso3389** [espresso3389/pdfrx#77]
![image](https://github.com/espresso3389/pdfrx/assets/1311400/2a52d09e-a6c4-4012-bd0a-13d45a19e658)

Actual error shown in "Pass static analysis" section:

```
The current Dart SDK version is 3.3.0-279.3.beta.
Because pdfrx requires SDK version >=3.3.0 <4.0.0, version solving failed.
```

If I fix the Dart SDK version to `3.3.0-279.3.beta`, the next is  Flutter SDK version to `3.19.0-0.4.pre`. And if fix both, it results in another error :(

**Comment by espresso3389** [comment]
https://github.com/dart-lang/pub-dev/issues/7484

**Comment by espresso3389** [comment]
[package:web 0.5.0](https://pub.dev/packages/web/versions/0.5.0) depends on `sdk: ^3.3.0-76.0.dev`:

https://github.com/dart-lang/web/blob/a54a1f0447979f9a3ea220199eca849ffb214e91/pubspec.yaml#L7

**Comment by espresso3389** [comment]
```
version: 1.0.5+test1
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.3.0-76.0.dev <4.0.0'
  flutter: '>=3.19.0-0.4.pre'
```

results in

```
The current Dart SDK version is 3.3.0-279.3.beta.
Because http >=1.2.1 requires SDK version ^3.3.0 and http >=1.1.2 <1.2.1 depends on web >=0.3.0 <0.5.0, http >=1.1.2 requires web >=0.3.0 <0.5.0.
```
